perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/news-commentary-v13.de-en.tok.de > ./2018/news-commentary-v13.de-en.tok.lower.de
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/news-commentary-v13.de-en.tok.en > ./2018/news-commentary-v13.de-en.tok.lower.en
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/paracrawl-release1.en-de.zipporah0-dedup-clean.tok.de > ./2018/paracrawl-release1.en-de.zipporah0-dedup-clean.tok.lower.de
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/paracrawl-release1.en-de.zipporah0-dedup-clean.tok.en > ./2018/paracrawl-release1.en-de.zipporah0-dedup-clean.tok.lower.en
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level/en_de/train.smt.tok.src > ./2018/sentence_level/en_de/train.smt.tok.lower.src
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level/en_de/train.smt.tok.pe > ./2018/sentence_level/en_de/train.smt.tok.lower.pe
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level/en_de/train.nmt.tok.src > ./2018/sentence_level/en_de/train.nmt.tok.lower.src
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level/en_de/train.nmt.tok.pe > ./2018/sentence_level/en_de/train.nmt.tok.lower.pe
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level/de_en/train.smt.tok.src > ./2018/sentence_level/de_en/train.smt.tok.lower.src
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level/de_en/train.smt.tok.pe > ./2018/sentence_level/de_en/train.smt.tok.lower.pe
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level_test/sentence_level/en_de/test.smt.tok.src > ./2018/sentence_level_test/sentence_level/en_de/test.smt.tok.lower.src
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level_test/sentence_level/en_de/test.smt.tok.mt > ./2018/sentence_level_test/sentence_level/en_de/test.smt.tok.lower.mt
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level_test/sentence_level/en_de/test.nmt.tok.src > ./2018/sentence_level_test/sentence_level/en_de/test.nmt.tok.lower.src
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level_test/sentence_level/en_de/test.nmt.tok.mt > ./2018/sentence_level_test/sentence_level/en_de/test.nmt.tok.lower.mt
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level_test/sentence_level/de_en/test.smt.tok.src > ./2018/sentence_level_test/sentence_level/de_en/test.smt.tok.lower.src
perl ./mosesdecoder-master/scripts/tokenizer/lowercase.perl < ./2018/sentence_level_test/sentence_level/de_en/test.smt.tok.mt > ./2018/sentence_level_test/sentence_level/de_en/test.smt.tok.lower.mt